version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0

jobs:
  deploy-and-test:
    executor: sfdx/default
    docker:
      - image: cimg/python:3.10.4-browsers
    resource_class: large
    steps:
      - sfdx/install
        version: "latest"
      - run:
          name: Install CumulusCI
          command: |
            pip install Cumulusci
      - run:
          name: authenticated DevHub
          command: |
            echo $SFDX_AUTH_DEVHUB > ~/devHub.auth
            sfdx auth:sfdxurl:store -f ~/devHub.auth \
                                        --setalias devHub \
                                        --setdefaultdevhubusername
      - checkout
      - run:
          name: Run Tests
          command: |
            cci task run robot --org dev
workflows:
  main:
    jobs:
      - deploy-and-test
