version: 2.1

jobs:
  deploy-and-test:
    executor: sfdx/default
    docker:
      - image: cimg/python:3.10.4-browsers
    resource_class: large
    steps:
      - sfdx/install

workflows:
  main:
    jobs:
      - deploy-and-test
