version: 2.1

jobs:
  deploy-and-test:
    docker:
      - image: cimg/python:3.10.4-browsers
    executor: sfdx/default
    executor_class: large
    steps:
      - sfdx/install
      - run:
          name: Update SFDX
          command: |
            sfdx update
            sfdx version

workflows:
  main:
    jobs:
      - deploy-and-test
